spring.application.name=EVALUATION-SERVICE
server.port=${EVALUATION_SERVICE_PORT:8094}

# H2 Database
spring.datasource.url=jdbc:h2:mem:evaluation-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Instance Eureka
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.instance.prefer-ip-address=${EUREKA_INSTANCE_PREFER_IP_ADDRESS:false}
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:localhost}

# Logs
logging.level.org.springframework=INFO
logging.level.com.netflix.eureka=DEBUG

# Config Server (optionnel)
spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

# RabbitMQ
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}
