CREATE DATABASE IF NOT EXISTS gestion_formation;
CREATE DATABASE IF NOT EXISTS projetdb;
CREATE DATABASE IF NOT EXISTS microservice;
CREATE DATABASE IF NOT EXISTS messagerie_db;
CREATE DATABASE IF NOT EXISTS condidature_db;

-- Grant root access from any host
ALTER USER 'root'@'localhost' IDENTIFIED BY '';
CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY '';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
