server.port=${CONFIG_SERVER_PORT:8888}
spring.application.name=config-server

# Native profile (serve from classpath:/config)
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=classpath:/config

# Remove Git config for local development stability
# spring.cloud.config.server.git.uri=https://github.com/hajerKhazri/config-repo.git

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
eureka.instance.hostname=localhost
eureka.instance.instance-id=${spring.application.name}:${server.port}
