server.port=8086
spring.application.name=SERVICE-PROJET

# Database
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/projetdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=${MYSQL_USERNAME:root}
spring.datasource.password=${MYSQL_PASSWORD:}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_URL:http://eureka-server:8761/eureka/}
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

# Logs
logging.level.org.springframework.amqp=INFO
logging.level.org.springframework.amqp.rabbit=INFO
