server:
  port: 8081

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:4200
              - http://127.0.0.1:4200
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: skills-service
          uri: lb://skills-service
          predicates:
            - Path=/skills/**

        - id: projet-service
          uri: lb://projet
          predicates:
            - Path=/projects/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
