server.port=${EUREKA_SERVER_PORT:8761}

spring.application.name=eureka-server

spring.cloud.config.fail-fast=false

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.wait-time-in-ms-when-sync-empty=0
